/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.digitalpiano;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author brstf
 */
public class PianoScreen extends javax.swing.JFrame {

    public void playMusic(String path) throws IOException {
        InputStream audio = new FileInputStream(new File(path));
        AudioStream audioStream = new AudioStream(audio);
        AudioPlayer.player.start(audioStream);
    }
    /**
     * Creates new form PianoScreen
     */
    public PianoScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        noteCs = new javax.swing.JButton();
        noteAs = new javax.swing.JButton();
        noteC1s = new javax.swing.JButton();
        noteC1 = new javax.swing.JButton();
        noteGs = new javax.swing.JButton();
        noteA = new javax.swing.JButton();
        noteFs = new javax.swing.JButton();
        noteDs = new javax.swing.JButton();
        noteG = new javax.swing.JButton();
        noteD = new javax.swing.JButton();
        noteF = new javax.swing.JButton();
        noteE = new javax.swing.JButton();
        noteC = new javax.swing.JButton();
        noteB = new javax.swing.JButton();
        noteD1s = new javax.swing.JButton();
        noteD1 = new javax.swing.JButton();
        noteE1 = new javax.swing.JButton();
        noteF1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 8));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel1KeyReleased(evt);
            }
        });
        jPanel1.setLayout(null);

        noteCs.setBackground(new java.awt.Color(0, 0, 0));
        noteCs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        noteCs.setForeground(new java.awt.Color(255, 255, 255));
        noteCs.setText("C#");
        noteCs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        noteCs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteCsActionPerformed(evt);
            }
        });
        jPanel1.add(noteCs);
        noteCs.setBounds(110, 250, 69, 210);
        noteCs.setFocusable(false);

        noteAs.setBackground(new java.awt.Color(0, 0, 0));
        noteAs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        noteAs.setForeground(new java.awt.Color(255, 255, 255));
        noteAs.setText("A#");
        noteAs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        noteAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteAsActionPerformed(evt);
            }
        });
        jPanel1.add(noteAs);
        noteAs.setBounds(510, 250, 70, 210);
        noteAs.setFocusable(false);

        noteC1s.setBackground(new java.awt.Color(0, 0, 0));
        noteC1s.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        noteC1s.setForeground(new java.awt.Color(255, 255, 255));
        noteC1s.setText("C#");
        noteC1s.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        noteC1s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteC1sActionPerformed(evt);
            }
        });
        jPanel1.add(noteC1s);
        noteC1s.setBounds(670, 250, 70, 210);
        noteC1s.setFocusable(false);

        noteC1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        noteC1.setText("C1");
        noteC1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        noteC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteC1ActionPerformed(evt);
            }
        });
        jPanel1.add(noteC1);
        noteC1.setBounds(630, 250, 70, 390);
        noteC1.setFocusable(false);

        noteGs.setBackground(new java.awt.Color(0, 0, 0));
        noteGs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        noteGs.setForeground(new java.awt.Color(255, 255, 255));
        noteGs.setText("G#");
        noteGs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        noteGs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteGsActionPerformed(evt);
            }
        });
        jPanel1.add(noteGs);
        noteGs.setBounds(430, 250, 70, 210);
        noteGs.setFocusable(false);

        noteA.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        noteA.setText("A");
        noteA.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        noteA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteAActionPerformed(evt);
            }
        });
        jPanel1.add(noteA);
        noteA.setBounds(470, 250, 70, 390);
        noteA.setFocusable(false);

        noteFs.setBackground(new java.awt.Color(0, 0, 0));
        noteFs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        noteFs.setForeground(new java.awt.Color(255, 255, 255));
        noteFs.setText("F#");
        noteFs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        noteFs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteFsActionPerformed(evt);
            }
        });
        jPanel1.add(noteFs);
        noteFs.setBounds(350, 250, 70, 210);
        noteFs.setFocusable(false);

        noteDs.setBackground(new java.awt.Color(0, 0, 0));
        noteDs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        noteDs.setForeground(new java.awt.Color(255, 255, 255));
        noteDs.setText("D#");
        noteDs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        noteDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteDsActionPerformed(evt);
            }
        });
        jPanel1.add(noteDs);
        noteDs.setBounds(190, 250, 70, 210);
        noteDs.setFocusable(false);

        noteG.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        noteG.setText("G");
        noteG.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        noteG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteGActionPerformed(evt);
            }
        });
        jPanel1.add(noteG);
        noteG.setBounds(390, 250, 70, 390);
        noteG.setFocusable(false);

        noteD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        noteD.setText("D");
        noteD.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        noteD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteDActionPerformed(evt);
            }
        });
        jPanel1.add(noteD);
        noteD.setBounds(150, 250, 70, 390);
        noteD.setFocusable(false);

        noteF.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        noteF.setText("F");
        noteF.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        noteF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteFActionPerformed(evt);
            }
        });
        jPanel1.add(noteF);
        noteF.setBounds(310, 250, 70, 390);
        noteF.setFocusable(false);

        noteE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        noteE.setText("E");
        noteE.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        noteE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteEActionPerformed(evt);
            }
        });
        jPanel1.add(noteE);
        noteE.setBounds(230, 250, 70, 390);
        noteE.setFocusable(false);

        noteC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        noteC.setText("C ");
        noteC.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        noteC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteCActionPerformed(evt);
            }
        });
        jPanel1.add(noteC);
        noteC.setBounds(70, 250, 70, 390);
        noteC.setFocusable(false);

        noteB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        noteB.setText("B");
        noteB.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        noteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteBActionPerformed(evt);
            }
        });
        jPanel1.add(noteB);
        noteB.setBounds(550, 250, 70, 390);
        noteB.setFocusable(false);

        noteD1s.setBackground(new java.awt.Color(0, 0, 0));
        noteD1s.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        noteD1s.setForeground(new java.awt.Color(255, 255, 255));
        noteD1s.setText("D#");
        noteD1s.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        noteD1s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteD1sActionPerformed(evt);
            }
        });
        jPanel1.add(noteD1s);
        noteD1s.setBounds(750, 250, 70, 210);
        noteD1s.setFocusable(false);

        noteD1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        noteD1.setText("D1");
        noteD1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        noteD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteD1ActionPerformed(evt);
            }
        });
        jPanel1.add(noteD1);
        noteD1.setBounds(710, 250, 70, 390);
        noteD1.setFocusable(false);

        noteE1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        noteE1.setText("E1");
        noteE1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        noteE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteE1ActionPerformed(evt);
            }
        });
        jPanel1.add(noteE1);
        noteE1.setBounds(790, 250, 70, 390);
        noteE1.setFocusable(false);

        noteF1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        noteF1.setText("F1");
        noteF1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        noteF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteF1ActionPerformed(evt);
            }
        });
        jPanel1.add(noteF1);
        noteF1.setBounds(870, 250, 70, 390);
        noteF1.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Virtual Piano");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 60, 870, 130);

        jPanel1.setFocusable(true);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(140, 70, 1030, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noteCsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteCsActionPerformed
        try{
            playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\C_s.wav");
        } catch (IOException e) {JOptionPane.showMessageDialog(null, e);}
        jPanel1.setFocusable(true);
    }//GEN-LAST:event_noteCsActionPerformed

    private void noteCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteCActionPerformed
        try{
            playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\C.wav");
        } catch (IOException e) {JOptionPane.showMessageDialog(null, e);}
        jPanel1.setFocusable(true);
    }//GEN-LAST:event_noteCActionPerformed

    private void noteDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteDActionPerformed
        try{
            playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\D.wav");
        } catch (IOException e) {JOptionPane.showMessageDialog(null, e);}
        jPanel1.setFocusable(true);
    }//GEN-LAST:event_noteDActionPerformed

    private void noteAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteAActionPerformed
        try{
            playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\A.wav");
        } catch (IOException e) {JOptionPane.showMessageDialog(null, e);}
        jPanel1.setFocusable(true);
    }//GEN-LAST:event_noteAActionPerformed

    private void noteGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteGActionPerformed
        try{
            playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\G.wav");
        } catch (IOException e) {JOptionPane.showMessageDialog(null, e);}
        jPanel1.setFocusable(true);
    }//GEN-LAST:event_noteGActionPerformed

    private void noteEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteEActionPerformed
        try{
            playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\E.wav");
        } catch (IOException e) {JOptionPane.showMessageDialog(null, e);}
        jPanel1.setFocusable(true);
    }//GEN-LAST:event_noteEActionPerformed

    private void noteFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteFActionPerformed
        try{
            playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\F.wav");
        } catch (IOException e) {JOptionPane.showMessageDialog(null, e);}
        jPanel1.setFocusable(true);
    }//GEN-LAST:event_noteFActionPerformed

    private void noteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteBActionPerformed
        try{
            playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\B.wav");
        } catch (IOException e) {JOptionPane.showMessageDialog(null, e);}
        jPanel1.setFocusable(true);
    }//GEN-LAST:event_noteBActionPerformed

    private void noteC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteC1ActionPerformed
        try{
            playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\C1.wav");
        } catch (IOException e) {JOptionPane.showMessageDialog(null, e);}
        jPanel1.setFocusable(true);
    }//GEN-LAST:event_noteC1ActionPerformed

    private void noteD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteD1ActionPerformed
        try{
            playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\D1.wav");
        } catch (IOException e) {JOptionPane.showMessageDialog(null, e);}
        jPanel1.setFocusable(true);
    }//GEN-LAST:event_noteD1ActionPerformed

    private void noteD1sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteD1sActionPerformed
        try{
            playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\D_s1.wav");
        } catch (IOException e) {JOptionPane.showMessageDialog(null, e);}
        jPanel1.setFocusable(true);
    }//GEN-LAST:event_noteD1sActionPerformed

    private void noteE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteE1ActionPerformed
        try{
            playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\E1.wav");
        } catch (IOException e) {JOptionPane.showMessageDialog(null, e);}
        jPanel1.setFocusable(true);
    }//GEN-LAST:event_noteE1ActionPerformed

    private void noteF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteF1ActionPerformed
        try{
            playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\F1.wav");
        } catch (IOException e) {JOptionPane.showMessageDialog(null, e);}
        jPanel1.setFocusable(true);
    }//GEN-LAST:event_noteF1ActionPerformed

    private void noteDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteDsActionPerformed
        try{
            playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\D_s.wav");
        } catch (IOException e) {JOptionPane.showMessageDialog(null, e);}
        jPanel1.setFocusable(true);
    }//GEN-LAST:event_noteDsActionPerformed

    private void noteFsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteFsActionPerformed
        try{
            playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\F_s.wav");
        } catch (IOException e) {JOptionPane.showMessageDialog(null, e);}
        jPanel1.setFocusable(true);
    }//GEN-LAST:event_noteFsActionPerformed

    private void noteGsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteGsActionPerformed
        try{
            playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\G_s.wav");
        } catch (IOException e) {JOptionPane.showMessageDialog(null, e);}
        jPanel1.setFocusable(true);
    }//GEN-LAST:event_noteGsActionPerformed

    private void noteAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteAsActionPerformed
        try{
            playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\Bb.wav");
        } catch (IOException e) {JOptionPane.showMessageDialog(null, e);}
        jPanel1.setFocusable(true);
    }//GEN-LAST:event_noteAsActionPerformed

    private void noteC1sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteC1sActionPerformed
        try{
            playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\C_s1.wav");
        } catch (IOException e) {JOptionPane.showMessageDialog(null, e);}
        jPanel1.setFocusable(true);
    }//GEN-LAST:event_noteC1sActionPerformed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        int keyCode = evt.getKeyCode();

        try{
            if(keyCode == java.awt.event.KeyEvent.VK_A) {
                playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\C.wav");
                noteC.setEnabled(false);
            }
            if(keyCode == java.awt.event.KeyEvent.VK_S) {
                playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\D.wav");
                noteD.setEnabled(false);
            }
            if(keyCode == java.awt.event.KeyEvent.VK_D) {
                playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\E.wav");
                noteE.setEnabled(false);
            }
            if(keyCode == java.awt.event.KeyEvent.VK_F) {
                playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\F.wav");
                noteF.setEnabled(false);
            }
            if(keyCode == java.awt.event.KeyEvent.VK_G) {
                playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\G.wav");
                noteG.setEnabled(false);
            }
            if(keyCode == java.awt.event.KeyEvent.VK_H) {
                playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\A.wav");
                noteA.setEnabled(false);
            }
            if(keyCode == java.awt.event.KeyEvent.VK_J) {
                playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\B.wav");
                noteB.setEnabled(false);
            }
            if(keyCode == java.awt.event.KeyEvent.VK_K) {
                playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\C1.wav");
                noteC1.setEnabled(false);
            }
            if(keyCode == java.awt.event.KeyEvent.VK_L) {
                playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\D1.wav");
                noteD1.setEnabled(false);
            }

            if(keyCode == java.awt.event.KeyEvent.VK_W) {
                playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\C_s.wav");
                noteCs.setEnabled(false);
            }
            if(keyCode == java.awt.event.KeyEvent.VK_E) {
                playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\D_s.wav");
                noteDs.setEnabled(false);
            }

            if(keyCode == java.awt.event.KeyEvent.VK_T) {
                playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\F_s.wav");
                noteFs.setEnabled(false);
            }
            if(keyCode == java.awt.event.KeyEvent.VK_Y) {
                playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\G_s.wav");
                noteGs.setEnabled(false);
            }
            if(keyCode == java.awt.event.KeyEvent.VK_U) {
                playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\Bb.wav");
                noteAs.setEnabled(false);
            }

            if(keyCode == java.awt.event.KeyEvent.VK_O) {
                playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\C_s1.wav");
                noteC1s.setEnabled(false);
            }
            if(keyCode == java.awt.event.KeyEvent.VK_P) {
                playMusic("C:\\Users\\brstf\\Documents\\NetBeansProjects\\DigitalPiano\\src\\main\\java\\com\\mycompany\\digitalpiano\\Music_Note\\D_s1.wav");
                noteD1s.setEnabled(false);
            }
        } catch (IOException e) {JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_jPanel1KeyPressed

    private void jPanel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyReleased
        int keyCode = evt.getKeyCode();

        //try{
            if(keyCode == java.awt.event.KeyEvent.VK_A)
                noteC.setEnabled(true);
            if(keyCode == java.awt.event.KeyEvent.VK_S)
                noteD.setEnabled(true);
            if(keyCode == java.awt.event.KeyEvent.VK_D)
                noteE.setEnabled(true);
            if(keyCode == java.awt.event.KeyEvent.VK_F)
                noteF.setEnabled(true);
            if(keyCode == java.awt.event.KeyEvent.VK_G)
                noteG.setEnabled(true);
            if(keyCode == java.awt.event.KeyEvent.VK_H)
                noteA.setEnabled(true);
            if(keyCode == java.awt.event.KeyEvent.VK_J)
                noteB.setEnabled(true);
            if(keyCode == java.awt.event.KeyEvent.VK_K)
                noteC1.setEnabled(true);
            if(keyCode == java.awt.event.KeyEvent.VK_L)
                noteD1.setEnabled(true);

            if(keyCode == java.awt.event.KeyEvent.VK_W)
                noteCs.setEnabled(true);
            if(keyCode == java.awt.event.KeyEvent.VK_E)
                noteDs.setEnabled(true);

            if(keyCode == java.awt.event.KeyEvent.VK_T)
                noteFs.setEnabled(true);
            if(keyCode == java.awt.event.KeyEvent.VK_Y)
                noteGs.setEnabled(true);
            if(keyCode == java.awt.event.KeyEvent.VK_U)
                noteAs.setEnabled(true);

            if(keyCode == java.awt.event.KeyEvent.VK_O)
                noteC1s.setEnabled(true);
            if(keyCode == java.awt.event.KeyEvent.VK_P)
                noteD1s.setEnabled(true);
        //} catch (IOException e) {JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_jPanel1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PianoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PianoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PianoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PianoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PianoScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton noteA;
    private javax.swing.JButton noteAs;
    private javax.swing.JButton noteB;
    private javax.swing.JButton noteC;
    private javax.swing.JButton noteC1;
    private javax.swing.JButton noteC1s;
    private javax.swing.JButton noteCs;
    private javax.swing.JButton noteD;
    private javax.swing.JButton noteD1;
    private javax.swing.JButton noteD1s;
    private javax.swing.JButton noteDs;
    private javax.swing.JButton noteE;
    private javax.swing.JButton noteE1;
    private javax.swing.JButton noteF;
    private javax.swing.JButton noteF1;
    private javax.swing.JButton noteFs;
    private javax.swing.JButton noteG;
    private javax.swing.JButton noteGs;
    // End of variables declaration//GEN-END:variables
}
